# Copyright (C) 2017 Felipe Alfaro Solana <felipe.alfaro@gmail.com>
#
# Ansible playbook: prepares the Ubuntu localhost machine (17.04+) for
# hosting LXD containers.
#
# Requirements:
# - Internet connectivity or proxy cache to install Ubuntu packages from
# - A logical volume group (VG) named "vg0" with at least 300GB of free
#   disk space.

- hosts: localhost
  tasks:
  - name: Ensure Git is installed
    package:
      name: git
  - name: Ensure VIM is installed
    package:
      name: vim
  - name: Ensure proper Git user e-mail for etckeeper
    git_config:
      name: user.email
      repo: /etc
      scope: global
      value: 'root@{{ ansible_fqdn }}'
  - name: Ensure proper Git user name for etckeeper
    git_config:
      name: user.name
      repo: /etc
      scope: local
      value: 'root'
  - name: Ensure etckeeper is installed
    package:
      name: etckeeper
  - name: Ensure logical volume for LXD exists
    lvol:
      vg: vg0
      lv: lxd
      size: 300G
  - name: Ensure btrfs filesystem in the logical volume for LXD exists
    filesystem:
      fstype: btrfs
      dev: /dev/vg0/lxd
      resizefs: no
  - name: Ensure logical volume for LXD is mounted at boot
    mount:
      fstype: btrfs
      opts: user_subvol_rm_allowed
      path: /var/lib/lxd
      src: /dev/vg0/lxd
      state: present
  - name: Ensure logical volume for LXD is mounted in /var/lib/lxd
    mount:
      fstype: btrfs
      src: /dev/vg0/lxd
      path: /var/lib/lxd
      state: mounted
  - name: Ensure LXD is installed
    package:
      name: "{{item}}"
    with_items:
      - lxd
      - lxd-client
  - name: Ensure LXD is running
    service:
      name: lxd
      state: started
      enabled: yes
  - name: Ensure LXD is initialized
    shell: "lxd init --network-address=0.0.0.0 --network-port=8443 --storage-backend=dir --auto"
  - name: Ensure LXD bridge exists
    shell: "lxc network create lxdbr0 ipv6.address=none ipv4.address=10.0.3.1/24 ipv4.nat=true"
    ignore_errors: true
  - name: Ensure default LXD profile attaches to LXD bridge
    shell: "lxc network attach-profile lxdbr0 default eth0"
    ignore_errors: true
  - name: Ensure cache LXD profile uses apt-cacher cache
    lxd_profile:
      name: cache
      state: present
      description: Use apt-cacher container
      config:
        boot.autostart: "true"
        user.user-data: |
          #cloud-config
          apt:
            proxy: http://cache:3142
  - name: Ensure nested LXD profile exists
    lxd_profile:
      name: nested
      state: present
      description: LXD container for nesting Docker/LXD
      config:
        security.privileged: "true"
        security.nesting: "true"
        linux.kernel_modules: "ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,openvswitch,nbd"
        raw.lxc: |
          lxc.aa_profile=unconfined
          lxc.mount.auto=sys:rw
          lxc.cap.drop=
  - name: Ensure the apt-cacher container exists
    lxd_container:
      name: cache
      state: started
      source:
        type: image
        mode: pull
        protocol: simplestreams
        server: "https://cloud-images.ubuntu.com/releases"
        alias: "17.04"
      profiles:
      - default
      wait_for_ipv4_addresses: true
      timeout: 600
  - name: Create a container
    lxd_container:
      name: openstack
      state: started
      source:
        type: image
        mode: pull
        protocol: simplestreams
        server: "https://cloud-images.ubuntu.com/releases"
        alias: "17.04"
      profiles:
      - cache
      - default
      - nested
      wait_for_ipv4_addresses: true
      timeout: 600
