- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create the Juju model
    shell: juju-2.0 add-model kubernetes
    ignore_errors: true
  - name: Ensure Juju's default LXD exists
    lxd_profile:
      name: juju-kubernetes
      state: present
      description: Juju's default LXD profile
      config:
        boot.autostart: "true"
        linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
        raw.lxc: |
          lxc.aa_profile=unconfined
          lxc.mount.auto=proc:rw sys:rw
          lxc.cap.drop=
        security.nesting: "true"
        security.privileged: "true"
      devices:
        aadisable:
          path: /sys/module/nf_conntrack/parameters/hashsize
          source: /dev/null
          type: disk
        aadisable1:
          path: /sys/module/apparmor/parameters/enabled
          source: /dev/null
          type: disk
