- hosts: localhost
  gather_facts: no
  vars:
  - container_name: kubernetes
  tasks:
  - name: Ensure Kubernetes container exists
    lxd_container:
      name: "{{container_name}}"
      state: started
      source:
        type: image
        mode: pull
        protocol: simplestreams
        server: "https://cloud-images.ubuntu.com/releases"
        alias: "17.04"
      profiles:
      - cache
      - docker
      - default
      - nested
      wait_for_ipv4_addresses: true
      timeout: 600
  - block:
    - name: Ensure Python is available in the container
      raw: "apt update && apt install -y python"
    - name: Remove LXD
      package:
        name: "{{item}}"
        state: absent
        use: apt
      with_items:
      - lxd
      - lxd-client
    - name: Install squashfuse in the container
      package:
        name: squashfuse
        use: apt
    - name: Ensure conjure-up is available in the container
      shell: "snap install conjure-up --classic"
    - name: Deploy Kubernetes inside the container
      shell: "conjure-up canonical-kubernetes localhost controller model"
      become: yes
      become_user: ubuntu
      tags: kube
    - name: Symlink kubecfg
      file:
        src: ~ubuntu/.kube/config.model
        dest: ~ubuntu/.kube/config
        state: link
        owner: ubuntu
        group: ubuntu
      tags: kube
    delegate_to: "{{container_name}}"
